"""
Comprehensive Test Script for Template CRUD Operations
Tests all template operations: Create, Read, Update, Delete, and Report Generation Integration
"""

import requests
import json
import sys
from datetime import datetime

# Configuration
BASE_URL = "http://localhost:5000"
API_BASE = f"{BASE_URL}/api/v1"

# Test user credentials (update with your actual test credentials)
TEST_USER = {
    "email": "test@example.com",
    "password": "testpassword123"
}

class TemplateAPITester:
    def __init__(self):
        self.session = requests.Session()
        self.auth_token = None
        self.created_template_id = None

    def print_header(self, text):
        """Print formatted test section header"""
        print("\n" + "=" * 60)
        print(f"  {text}")
        print("=" * 60)

    def print_result(self, success, message):
        """Print test result"""
        icon = "✅" if success else "❌"
        print(f"{icon} {message}")

    def authenticate(self):
        """Authenticate and get token"""
        self.print_header("AUTHENTICATION TEST")

        try:
            # Try Firebase auth first
            response = self.session.post(
                f"{BASE_URL}/auth/firebase/login",
                json=TEST_USER
            )

            if response.status_code == 200:
                data = response.json()
                self.auth_token = data.get('idToken') or data.get('token')
                self.session.headers.update({
                    'Authorization': f'Bearer {self.auth_token}'
                })
                self.print_result(True, f"Authenticated successfully")
                return True
            else:
                self.print_result(False, f"Authentication failed: {response.status_code}")
                print(f"Response: {response.text}")
                return False

        except Exception as e:
            self.print_result(False, f"Authentication error: {str(e)}")
            return False

    def test_get_templates(self):
        """Test GET /api/v1/templates"""
        self.print_header("TEST: GET All Templates")

        try:
            response = self.session.get(f"{API_BASE}/templates")

            if response.status_code == 200:
                data = response.json()
                templates = data.get('templates', [])
                self.print_result(True, f"Retrieved {len(templates)} templates")

                # Display template details
                for template in templates[:3]:  # Show first 3
                    print(f"  - {template['name']} (ID: {template['id']}, Type: {template.get('template_type', 'N/A')})")

                return True
            else:
                self.print_result(False, f"Failed to get templates: {response.status_code}")
                print(f"Response: {response.text}")
                return False

        except Exception as e:
            self.print_result(False, f"Error: {str(e)}")
            return False

    def test_create_template(self):
        """Test POST /api/v1/templates"""
        self.print_header("TEST: CREATE New Template")

        template_data = {
            "name": f"Test Template {datetime.now().strftime('%Y%m%d_%H%M%S')}",
            "description": "This is a test template created by automated testing",
            "category": "business",
            "template_type": "jinja2",
            "template_content": """
<html>
<head><title>{{company_name}} Report</title></head>
<body>
    <h1>{{report_title}}</h1>
    <p>Date: {{report_date}}</p>
    <div class="content">
        {{content}}
    </div>
    <footer>Generated by {{author}}</footer>
</body>
</html>
            """.strip(),
            "variables": [
                {"name": "company_name", "type": "string", "required": True},
                {"name": "report_title", "type": "string", "required": True},
                {"name": "report_date", "type": "date", "required": False},
                {"name": "content", "type": "text", "required": True},
                {"name": "author", "type": "string", "required": False}
            ],
            "supports_excel": True,
            "required_fields": ["company_name", "report_title", "content"]
        }

        try:
            response = self.session.post(
                f"{API_BASE}/templates",
                json=template_data
            )

            if response.status_code == 201:
                data = response.json()
                template = data.get('template', {})
                self.created_template_id = template.get('id')
                self.print_result(True, f"Created template with ID: {self.created_template_id}")
                print(f"  Name: {template.get('name')}")
                print(f"  Type: {template.get('template_type')}")
                print(f"  Category: {template.get('category')}")
                return True
            else:
                self.print_result(False, f"Failed to create template: {response.status_code}")
                print(f"Response: {response.text}")
                return False

        except Exception as e:
            self.print_result(False, f"Error: {str(e)}")
            return False

    def test_get_single_template(self):
        """Test GET /api/v1/templates/<id>"""
        self.print_header("TEST: GET Single Template")

        if not self.created_template_id:
            self.print_result(False, "No template ID available (create test must run first)")
            return False

        try:
            response = self.session.get(f"{API_BASE}/templates/{self.created_template_id}")

            if response.status_code == 200:
                data = response.json()
                template = data.get('template', {})
                self.print_result(True, f"Retrieved template: {template.get('name')}")
                print(f"  Description: {template.get('description')}")
                print(f"  Variables: {len(template.get('variables', []))}")
                return True
            else:
                self.print_result(False, f"Failed to get template: {response.status_code}")
                print(f"Response: {response.text}")
                return False

        except Exception as e:
            self.print_result(False, f"Error: {str(e)}")
            return False

    def test_update_template(self):
        """Test PUT /api/v1/templates/<id>"""
        self.print_header("TEST: UPDATE Template")

        if not self.created_template_id:
            self.print_result(False, "No template ID available (create test must run first)")
            return False

        update_data = {
            "name": f"Updated Test Template {datetime.now().strftime('%H%M%S')}",
            "description": "This template has been updated by automated testing"
        }

        try:
            response = self.session.put(
                f"{API_BASE}/templates/{self.created_template_id}",
                json=update_data
            )

            if response.status_code == 200:
                data = response.json()
                template = data.get('template', {})
                self.print_result(True, f"Updated template: {template.get('name')}")
                return True
            else:
                self.print_result(False, f"Failed to update template: {response.status_code}")
                print(f"Response: {response.text}")
                return False

        except Exception as e:
            self.print_result(False, f"Error: {str(e)}")
            return False

    def test_rename_template(self):
        """Test renaming a template (special case of update)"""
        self.print_header("TEST: RENAME Template")

        if not self.created_template_id:
            self.print_result(False, "No template ID available (create test must run first)")
            return False

        rename_data = {
            "name": f"Renamed Template {datetime.now().strftime('%H%M%S')}"
        }

        try:
            response = self.session.put(
                f"{API_BASE}/templates/{self.created_template_id}",
                json=rename_data
            )

            if response.status_code == 200:
                data = response.json()
                template = data.get('template', {})
                self.print_result(True, f"Renamed template to: {template.get('name')}")
                return True
            else:
                self.print_result(False, f"Failed to rename template: {response.status_code}")
                print(f"Response: {response.text}")
                return False

        except Exception as e:
            self.print_result(False, f"Error: {str(e)}")
            return False

    def test_template_in_report_generation(self):
        """Test that created template appears in report generation endpoints"""
        self.print_header("TEST: Template Available for Report Generation")

        try:
            # Check if template appears in the templates list
            response = self.session.get(f"{API_BASE}/templates")

            if response.status_code == 200:
                data = response.json()
                templates = data.get('templates', [])

                # Look for our created template
                found = False
                for template in templates:
                    if template['id'] == self.created_template_id:
                        found = True
                        self.print_result(True, f"Template is available for report generation")
                        print(f"  Template: {template['name']}")
                        print(f"  Status: Active={template.get('is_active', False)}")
                        break

                if not found:
                    self.print_result(False, "Template not found in active templates list")
                    return False

                return True
            else:
                self.print_result(False, f"Failed to verify template availability: {response.status_code}")
                return False

        except Exception as e:
            self.print_result(False, f"Error: {str(e)}")
            return False

    def test_delete_template(self):
        """Test DELETE /api/v1/templates/<id>"""
        self.print_header("TEST: DELETE Template")

        if not self.created_template_id:
            self.print_result(False, "No template ID available (create test must run first)")
            return False

        try:
            response = self.session.delete(f"{API_BASE}/templates/{self.created_template_id}")

            if response.status_code == 200:
                self.print_result(True, "Template deleted successfully")

                # Verify it's no longer in active templates
                get_response = self.session.get(f"{API_BASE}/templates")
                if get_response.status_code == 200:
                    templates = get_response.json().get('templates', [])
                    found = any(t['id'] == self.created_template_id for t in templates)

                    if not found:
                        self.print_result(True, "Verified: Template is no longer in active list")
                    else:
                        self.print_result(False, "Warning: Template still appears in active list")

                return True
            else:
                self.print_result(False, f"Failed to delete template: {response.status_code}")
                print(f"Response: {response.text}")
                return False

        except Exception as e:
            self.print_result(False, f"Error: {str(e)}")
            return False

    def run_all_tests(self):
        """Run all tests in sequence"""
        print("\n" + "=" * 60)
        print("  TEMPLATE CRUD OPERATIONS - COMPREHENSIVE TEST SUITE")
        print("=" * 60)
        print(f"  Base URL: {BASE_URL}")
        print(f"  Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        print("=" * 60)

        results = {
            "Authentication": self.authenticate(),
            "Get All Templates": self.test_get_templates(),
            "Create Template": self.test_create_template(),
            "Get Single Template": self.test_get_single_template(),
            "Update Template": self.test_update_template(),
            "Rename Template": self.test_rename_template(),
            "Template in Report Generation": self.test_template_in_report_generation(),
            "Delete Template": self.test_delete_template(),
        }

        # Print summary
        self.print_header("TEST SUMMARY")
        passed = sum(1 for v in results.values() if v)
        total = len(results)

        for test_name, result in results.items():
            self.print_result(result, test_name)

        print("\n" + "=" * 60)
        print(f"  RESULTS: {passed}/{total} tests passed")
        print(f"  Completed: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        print("=" * 60)

        return passed == total


if __name__ == "__main__":
    print("\n🧪 Starting Template CRUD Test Suite...\n")

    tester = TemplateAPITester()
    success = tester.run_all_tests()

    sys.exit(0 if success else 1)
